### PR TITLE
block more trash

### PR DESCRIPTION
**Pull request by Nyameliaaaa**
lets make this a cringe free world!

### CODE REVIEW

**Comment by Nyameliaaaa** [comment]
@PradyX

**Comment by TheGreatRambler** [comment]
This man is ruthless :eyes:

**Review by voidlynx — CHANGES_REQUESTED** [review]
tho you are trying to remove apps that reddit does not like, you should still know that people use those to communicate/have fun. so that is useless.

**Comment by Nyameliaaaa** [comment]
Every social app is trash

**Comment by Nyameliaaaa** [comment]
@PradyX I have updated it to block short video apps and stinky garbage

**Comment by PradyX** [comment]
Closing cuz it's way too harsh lol

**Comment by Nyameliaaaa** [comment]
> Closing cuz it's way too harsh lol

You TikTok spy.

**Pull request closed without merging**
